Adding CONTRIBUTING.md file
dafky2000/simplectemplate pull request #9
Opened 2017-10-15 13:49 UTC by Supun94

PR for issue #3

2017-10-15 14:26 UTC, dafky2000 commented
at first glance there are a couple things i would like to change. will review and discuss changes later on today! thank you!!

2017-10-16 00:51 UTC, dafky2000 commented on CONTRIBUTING.md
> +* All changes to the code should have appropriate unit tests
Lets delete this one for now until #2 is done.

2017-10-16 00:57 UTC, dafky2000 commented on CONTRIBUTING.md
> +* All code should match PSR-2 style
Please remove above for now, I will update with my fussy coding style after #6

2017-10-16 00:59 UTC, dafky2000 commented on CONTRIBUTING.md
> +* All travis checks will need to pass
Again, above is not applicable right now. I have created #12 and will add after that is complete.

2017-10-16 01:02 UTC, dafky2000 commented on CONTRIBUTING.md
> +#### **Did you write a patch that fixes a bug?**
Let's remove this section, maybe change the title of "Pull Request Process" to something else - "Fixing issues & Pull request process"?

2017-10-16 01:04 UTC, dafky2000 commented on CONTRIBUTING.md
> +#### **Do you intend to add a new feature or change an existing one?**
Let's get rid of this section, I don't mind getting feature requests (as long as they aren't duplicated) as a method of getting some initial feedback.

2017-10-16 01:05 UTC, dafky2000 requested changes
@Supun94, I have made some notes about my review. Overall it is great! Just a few small changes if you don't mind :)

2017-10-16 04:09 UTC, Supun94 commented
@dafky2000 I have done the necessary changes. Please review :)

2017-10-16 11:05 UTC, dafky2000 approved these changes
Thank you @Supun94!

2017-10-16 11:05 UTC, merged